#!/usr/bin/env python


from __future__ import print_function
from __future__ import unicode_literals

import os
import sys


from hermit.sourceparser import parse
from hermit.astcompiler import compile_ast


args = iter(sys.argv)
next(args)  # program name

arg = next(args, None)
if arg in (None, "-"):
    name = "<stdin>"
    source = sys.stdin.read()
elif os.path.exists(arg):
    name = arg
    source = open(arg, "r").read()
else:
    name = "<input>"
    source = arg

print("Source:")
for i, line in enumerate(source.split("\n")):
    print("{line:>3} {text}".format(line=(i + 1), text=line))
print()

ast = parse(source)
bc = compile_ast(name, source, ast)

print("Bytecode:")
for i, line in enumerate(bc.dump().split("\n")):
    print("{line:>3} {text}".format(line=(i + 1), text=line))
print()
